config/routes.rb
# == Route Map
#
#                  Prefix Verb   URI Pattern                                   Controller#Action
#     new_manager_session GET    /managers/sign_in(.:format)                   managers/sessions#new
#         manager_session POST   /managers/sign_in(.:format)                   managers/sessions#create
# destroy_manager_session DELETE /managers/sign_out(.:format)                  managers/sessions#destroy
#        parties_managers GET    /managers/parties(.:format)                   managers#parties
#                         GET    /managers/parties/:id(.:format)               managers#judge
#                         POST   /managers/parties/:id/:state(.:format)        managers#result
#                managers GET    /managers(.:format)                           managers#index
#                         POST   /managers(.:format)                           managers#create
#             new_manager GET    /managers/new(.:format)                       managers#new
#            edit_manager GET    /managers/:id/edit(.:format)                  managers#edit
#                 manager GET    /managers/:id(.:format)                       managers#show
#                         PATCH  /managers/:id(.:format)                       managers#update
#                         PUT    /managers/:id(.:format)                       managers#update
#                         DELETE /managers/:id(.:format)                       managers#destroy
#      party_participants GET    /parties/:party_id/participants(.:format)     participants#index
#                         POST   /parties/:party_id/participants(.:format)     participants#create
#   new_party_participant GET    /parties/:party_id/participants/new(.:format) participants#new
#       party_participant GET    /parties/:party_id/participants/:id(.:format) participants#show
#                         PATCH  /parties/:party_id/participants/:id(.:format) participants#update
#                         PUT    /parties/:party_id/participants/:id(.:format) participants#update
#                 parties GET    /parties(.:format)                            parties#index
#                         POST   /parties(.:format)                            parties#create
#               new_party GET    /parties/new(.:format)                        parties#new
#              edit_party GET    /parties/:id/edit(.:format)                   parties#edit
#                   party GET    /parties/:id(.:format)                        parties#show
#                         PATCH  /parties/:id(.:format)                        parties#update
#                         PUT    /parties/:id(.:format)                        parties#update
#                         DELETE /parties/:id(.:format)                        parties#destroy
#                kitchens GET    /kitchens(.:format)                           kitchens#index
#                         POST   /kitchens(.:format)                           kitchens#create
#             new_kitchen GET    /kitchens/new(.:format)                       kitchens#new
#            edit_kitchen GET    /kitchens/:id/edit(.:format)                  kitchens#edit
#                 kitchen GET    /kitchens/:id(.:format)                       kitchens#show
#                         PATCH  /kitchens/:id(.:format)                       kitchens#update
#                         PUT    /kitchens/:id(.:format)                       kitchens#update
#                         DELETE /kitchens/:id(.:format)                       kitchens#destroy
#               introduce GET    /introduce(.:format)                          home#introduce
#                   guide GET    /guide(.:format)                              home#guide
#                    root GET    /                                             parties#index
#

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :managers, module: 'managers', only: :sessions

  resources :managers do
    collection do
      get 'parties', to: 'managers#parties'
      get 'parties/:id', to: 'managers#judge'
      post 'parties/:id/:state', to: 'managers#result'
    end
  end

  resources :parties do
    resources :participants, only: %i(index new create show update) do
    end
  end

  resources :kitchens do
  end

  get 'introduce', to: 'home#introduce'
  get 'guide', to: 'home#guide'
  root to: 'parties#index', as: :root
end

app/models/kitchen.rb
# == Schema Information
#
# Table name: kitchens
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  address      :string(255)
#  phone        :string(255)
#  email        :string(255)
#  maxPerson    :integer
#  spaceType    :integer
#  equipment    :string(255)
#  opening_time :string(255)
#  closed_time  :string(255)
#  fare         :string(255)
#  etc          :string(255)
#  notice       :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  latitute     :float(53)        default(0.0)
#  longitute    :float(53)        default(0.0)
#

class Kitchen < ApplicationRecord

  validates :name, :address, :phone, :email, presence: true

  enum spaceType: {
      # TODO: fill
  }
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  before_action :set_kitchen, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, only: %i(create edit update destroy)

  # GET /kitchens
  # GET /kitchens.json
  def index
    @kitchens = Kitchen.all
  end

  # GET /kitchens/1
  # GET /kitchens/1.json
  def show
  end

  # GET /kitchens/new
  def new
    @kitchen = Kitchen.new
  end

  # GET /kitchens/1/edit
  def edit
  end

  # POST /kitchens
  # POST /kitchens.json
  def create
    @kitchen = Kitchen.new(kitchen_params)

    respond_to do |format|
      if @kitchen.save
        format.html { redirect_to @kitchen, notice: 'Kitchen was successfully created.' }
        format.json { render :show, status: :created, location: @kitchen }
      else
        format.html { render :new }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitchens/1
  # PATCH/PUT /kitchens/1.json
  def update
    respond_to do |format|
      if @kitchen.update(kitchen_params)
        format.html { redirect_to @kitchen, notice: 'Kitchen was successfully updated.' }
        format.json { render :show, status: :ok, location: @kitchen }
      else
        format.html { render :edit }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitchens/1
  # DELETE /kitchens/1.json
  def destroy
    @kitchen.destroy
    respond_to do |format|
      format.html { redirect_to kitchens_url, notice: 'Kitchen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitchen
      @kitchen = Kitchen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitchen_params
      params.require(:kitchen).permit(:name, :address, :phone, :email, :maxPerson, :spaceType, :equipment, :opening_time, :closed_time, :fare, :etc, :notice)
    end
end

app/views/kitchens/_form.html.erb
<%= form_for(kitchen) do |f| %>
  <% if kitchen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kitchen.errors.count, "error") %> prohibited this kitchen from being saved:</h2>

      <ul>
      <% kitchen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :maxPerson %>
    <%= f.number_field :maxPerson %>
  </div>

  <div class="field">
    <%= f.label :spaceType %>
    <%= f.number_field :spaceType %>
  </div>

  <div class="field">
    <%= f.label :equipment %>
    <%= f.text_field :equipment %>
  </div>

  <div class="field">
    <%= f.label :opening_time %>
    <%= f.text_field :opening_time %>
  </div>

  <div class="field">
    <%= f.label :closed_time %>
    <%= f.text_field :closed_time %>
  </div>

  <div class="field">
    <%= f.label :fare %>
    <%= f.text_field :fare %>
  </div>

  <div class="field">
    <%= f.label :etc %>
    <%= f.text_field :etc %>
  </div>

  <div class="field">
    <%= f.label :notice %>
    <%= f.text_field :notice %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kitchens/edit.html.erb
<h1>Editing Kitchen</h1>

<%= render 'form', kitchen: @kitchen %>

<%= link_to 'Show', @kitchen %> |
<%= link_to 'Back', kitchens_path %>

app/views/kitchens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kitchens</h1>

<div id="map" style="width:100%;height:350px;"></div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Maxperson</th>
      <th>Spacetype</th>
      <th>Equipment</th>
      <th>Opening time</th>
      <th>Closed time</th>
      <th>Fare</th>
      <th>Etc</th>
      <th>Notice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kitchens.each do |kitchen| %>
      <tr>
        <td><%= kitchen.name %></td>
        <td><%= kitchen.address %></td>
        <td><%= kitchen.phone %></td>
        <td><%= kitchen.email %></td>
        <td><%= kitchen.maxPerson %></td>
        <td><%= kitchen.spaceType %></td>
        <td><%= kitchen.equipment %></td>
        <td><%= kitchen.opening_time %></td>
        <td><%= kitchen.closed_time %></td>
        <td><%= kitchen.fare %></td>
        <td><%= kitchen.etc %></td>
        <td><%= kitchen.notice %></td>
        <td><%= link_to 'Show', kitchen %></td>
        <td><%= link_to 'Edit', edit_kitchen_path(kitchen) %></td>
        <td><%= link_to 'Destroy', kitchen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<script type="text/javascript" src="//apis.daum.net/maps/maps3.js?apikey=8b5c466ea7f19195aab58ee5c6810912"></script>
<script>
var positions = [];
var latitute = 0;
var longitute = 0;
<% @kitchens.each do |kitchen| %>
    positions.push({ title: '<%=kitchen.name%>', latlng: new daum.maps.LatLng(<%=kitchen.latitute%>, <%=kitchen.longitute%>) });
    latitute += <%=kitchen.latitute%>;
    longitute += <%=kitchen.longitute%>;
<% end %>
var mapContainer = document.getElementById('map'),  
    mapOption = { 
        center: new daum.maps.LatLng(latitute / positions.length, longitute / positions.length), // 지도의 중심좌표
        level: 10
    };
var map = new daum.maps.Map(mapContainer, mapOption); // 지도를 생성합니다
 
for (var i = 0; i < positions.length; i ++) {
    new daum.maps.Marker({ map: map, position: positions[i].latlng, title : positions[i].title });
}
</script>

<%= link_to 'New Kitchen', new_kitchen_path %>

app/views/kitchens/new.html.erb
<h1>New Kitchen</h1>

<%= render 'form', kitchen: @kitchen %>

<%= link_to 'Back', kitchens_path %>

app/views/kitchens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kitchen.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @kitchen.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @kitchen.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @kitchen.email %>
</p>

<p>
  <strong>Maxperson:</strong>
  <%= @kitchen.maxPerson %>
</p>

<p>
  <strong>Spacetype:</strong>
  <%= @kitchen.spaceType %>
</p>

<p>
  <strong>Equipment:</strong>
  <%= @kitchen.equipment %>
</p>

<p>
  <strong>Opening time:</strong>
  <%= @kitchen.opening_time %>
</p>

<p>
  <strong>Closed time:</strong>
  <%= @kitchen.closed_time %>
</p>

<p>
  <strong>Fare:</strong>
  <%= @kitchen.fare %>
</p>

<p>
  <strong>Etc:</strong>
  <%= @kitchen.etc %>
</p>

<p>
  <strong>Notice:</strong>
  <%= @kitchen.notice %>
</p>


<div id="map" style="width:100%;height:350px;"></div>

<script type="text/javascript" src="//apis.daum.net/maps/maps3.js?apikey=8b5c466ea7f19195aab58ee5c6810912"></script>
<script>    
var markers = [
    { position: new daum.maps.LatLng(<%= @kitchen.latitute %>, <%= @kitchen.longitute %>), text: '<%= @kitchen.name %>' }
];
var staticMapContainer  = document.getElementById('map'),  
    staticMapOption = { 
        center: new daum.maps.LatLng(<%= @kitchen.latitute %>, <%= @kitchen.longitute %>),
        level: 3, // 이미지 지도의 확대 레벨
        marker: markers // 이미지 지도에 표시할 마커 
    };    
new daum.maps.StaticMap(staticMapContainer, staticMapOption);
</script>


<%= link_to 'Edit', edit_kitchen_path(@kitchen) %> |
<%= link_to 'Back', kitchens_path %>