config/routes.rb
# == Route Map
#
#                  Prefix Verb   URI Pattern                                   Controller#Action
#     new_manager_session GET    /managers/sign_in(.:format)                   managers/sessions#new
#         manager_session POST   /managers/sign_in(.:format)                   managers/sessions#create
# destroy_manager_session DELETE /managers/sign_out(.:format)                  managers/sessions#destroy
#        parties_managers GET    /managers/parties(.:format)                   managers#parties
#                         GET    /managers/parties/:id(.:format)               managers#judge
#                         POST   /managers/parties/:id/:state(.:format)        managers#result
#                managers GET    /managers(.:format)                           managers#index
#                         POST   /managers(.:format)                           managers#create
#             new_manager GET    /managers/new(.:format)                       managers#new
#            edit_manager GET    /managers/:id/edit(.:format)                  managers#edit
#                 manager GET    /managers/:id(.:format)                       managers#show
#                         PATCH  /managers/:id(.:format)                       managers#update
#                         PUT    /managers/:id(.:format)                       managers#update
#                         DELETE /managers/:id(.:format)                       managers#destroy
#      party_participants GET    /parties/:party_id/participants(.:format)     participants#index
#                         POST   /parties/:party_id/participants(.:format)     participants#create
#   new_party_participant GET    /parties/:party_id/participants/new(.:format) participants#new
#       party_participant GET    /parties/:party_id/participants/:id(.:format) participants#show
#                         PATCH  /parties/:party_id/participants/:id(.:format) participants#update
#                         PUT    /parties/:party_id/participants/:id(.:format) participants#update
#                 parties GET    /parties(.:format)                            parties#index
#                         POST   /parties(.:format)                            parties#create
#               new_party GET    /parties/new(.:format)                        parties#new
#              edit_party GET    /parties/:id/edit(.:format)                   parties#edit
#                   party GET    /parties/:id(.:format)                        parties#show
#                         PATCH  /parties/:id(.:format)                        parties#update
#                         PUT    /parties/:id(.:format)                        parties#update
#                         DELETE /parties/:id(.:format)                        parties#destroy
#                kitchens GET    /kitchens(.:format)                           kitchens#index
#                         POST   /kitchens(.:format)                           kitchens#create
#             new_kitchen GET    /kitchens/new(.:format)                       kitchens#new
#            edit_kitchen GET    /kitchens/:id/edit(.:format)                  kitchens#edit
#                 kitchen GET    /kitchens/:id(.:format)                       kitchens#show
#                         PATCH  /kitchens/:id(.:format)                       kitchens#update
#                         PUT    /kitchens/:id(.:format)                       kitchens#update
#                         DELETE /kitchens/:id(.:format)                       kitchens#destroy
#               introduce GET    /introduce(.:format)                          home#introduce
#                   guide GET    /guide(.:format)                              home#guide
#                    root GET    /                                             parties#index
#

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :managers, module: 'managers', only: :sessions

  resources :managers do
    collection do
      get 'parties', to: 'managers#parties'
      get 'parties/:id', to: 'managers#judge'
      post 'parties/:id/:state', to: 'managers#result'
    end
  end

  resources :parties do
    resources :participants, only: %i(index new create show update) do
    end
  end

  resources :kitchens do
  end

  get 'introduce', to: 'home#introduce'
  get 'guide', to: 'home#guide'
  root to: 'parties#index', as: :root
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=@title%>::끼니를 다함께</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:author" content="끼다" />
    <meta property="og:site_name" content="끼니를 다함께" />
    <meta property="og:title" content="<%=@title || "끼니를 다함께"%>"/>
    <meta property="og:image" content="<%=@thumbnail || "http://ggida.org/images/meta_ggida.png"%>" />
    <meta property="og:description" content="<%=@description || "함께 만드는 요리의 재미, 끼다! &lt;끼다&gt;는 정부 및 지자체를 중심으로 만들어진 공유부엌을 이용하여 1인 가구 청년들이 보다 즐겁고, 건강하게 함께 밥을 먹을 수 있도록 만든 공유부엌 활성화 플랫폼입니다."%>" />

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
	@media only screen and (min-width: 768px) {
		.list_contact .thumb_g{height:157px;overflow:hidden}
	}
    </style>
  </head>

  <body>

  <div id="kakaoIndex">
    <a href="#kakaoBody">본문 바로가기</a>
    <a href="#kakaoGnb">메뉴 바로가기</a>
  </div>
  <div id="ggidaWrap" class="<%=@style || "cont_sub"%>">
    <div id="ggidaHead" class="ggida_head " role="banner"> <!-- box_visual 영역 사라지면 fixed_head 클래스 추가-->
      <div class="inner_head">
        <% if current_page?(new_manager_session_path) %>
            <h1 class="tit_head"><a href="/" class="link_logo"><span class="ico_ggida tit_logo">ggida</span></a></h1>
            <h2 class="screen_out">Manager Login</h2>
        <% else %>
            <h1 class="tit_logo"><img src="/images/m640/img_logo_pc.png" class="img_logo" alt="끼다"></h1>
            <a href="javascript:;" class="btn_ggida btn_navi"><span class="ico_ggida ico_navi">메뉴열기</span></a>
            <div id="ggidaGnb" role="navigation">
              <h2 class="screen_out">끼다 메인메뉴</h2>
              <ul class="gnb_ggida">
                <li><a href="/" class="link_gnb">HOME</a></li>
                <% if current_manager %>
                    <li><a href="/managers/parties" class="link_gnb">신청모임확인</a></li>
                <% else %>
                    <li><a href="/parties/new" class="link_gnb">모임개설신청</a></li>
                <% end %>
                <li><a href="/introduce" class="link_gnb">끼다소개</a></li>
                <li><a href="/guide" class="link_gnb">사용안내</a></li>
              </ul>
              <% if current_manager %>
                  <a href="javascript:;" class="link_gnb btn_logout">로그아웃</a>
              <% end %>
              <button type="button" class="btn_ggida btn_close"><span class="ico_ggida ico_close">메뉴 닫기</span></button>
            </div>
        <% end %>
      </div>
    </div>  <!-- //header-->

    <div id="ggidaContent" class="cont_main" role="main">
      <div id="cMain">
        <div id="mFeature">
          <div class="side_menu navi_on" style="left:-1000px"> <!-- 모바일(w768미)dptj 메뉴 열때 navi_on 클래스 추가 -->
            <ul class="gnb_ggida">
              <li><a href="/" class="link_gnb">HOME</a></li>
              <% if current_manager %>
                  <li><a href="/managers/parties" class="link_gnb">신청모임확인</a></li>
              <% else %>
                  <li><a href="/parties/new" class="link_gnb">모임개설신청</a></li>
              <% end %>
              <li><a href="/introduce" class="link_gnb">끼다소개</a></li>
              <li><a href="/guide" class="link_gnb">사용안내</a></li>
              <% if current_manager %>
                  <li><a href="javascript:;" class="link_gnb btn_logout2">로그아웃</a></li>
              <% end %>
            </ul>
            <button type="button" class="btn_ggida btn_close"><span class="ico_ggida ico_close">메뉴 닫기</span></button>
          </div>
        </div>
        <% if current_page?(root_path) %>
          <div id="mSub">
            <div class="box_visual">
              <img src="/images/m640/bg_top.png" class="bg_img" alt="">
              <div class="inner_g">
                <img src="/images/m640/img_logo_ff.png" class="logo_img" alt="끼다 로고">
                <strong class="tit_visual">함께 만드는 요리의 재미, 끼다!</strong>
                <p class="txt_info">&#60;끼다&#62;는 정부 및 지자체를 중심으로 만들어진<br> 공유부엌을 이용하여 1인 가구 청년들이 보다<br>즐겁고, 건강하게 함께 밥을 먹을 수 있도록 만든<br>공유부엌 활성화 플랫폼입니다.</p>
              </div>
            </div>
          </div>
        <% end %>
        <%= yield %> <!-- 본문부분 -->
      </div>
    </div>
    <!-- 여기까지 푸터 -->
    <div id="ggidaFoot"></div> <!-- //Footer -->
  </div>
  <script type="text/javascript">
    $(document).ready(function() {
      var Scroll = (function() {
        return {
          enable: function() {
            $('body').css('overflow-y', 'visible');
          },
          disable: function() {
            $('body').css('overflow-y', 'hidden');
          }
        }
      })();

      var Header = (function() {
        var opener = $(".btn_navi");
        var elem = $("#mFeature");
        var closeButton = elem.find(".btn_close");
        var navigator = elem.find(".side_menu");
        var logoutButton = elem.find(".btn_logout .btn_logout2");
        (function init() {
          opener.click(function() {
            var wH = $(window).height();
            navigator.show();
            $(".cont_top").addClass("navi_on");
            Scroll.disable();
            navigator.css('height', wH);
          });
          closeButton.click(function() {
            navigator.hide();
            $(".cont_top").removeClass("navi_on");
            Scroll.enable();
          });
          logoutButton.click(function() {
            $.ajax( {
              url: '/managers/sign_out',
              type: 'DELETE',
              success: function(result) {
                window.location.href = "/managers/sign_in";
              },
              error: function(error) {
                console.log(error);
              }
            });
          });
        })();
      })();
    });
  </script>
  </body>
</html>